### ISSUE TITLE
Where are the icons from?  I'd like to add Github to them and trying to have it match the others.

### ISSUE THREAD

**Issue by epetre** [ixartz/astro-boilerplate-components#4]
Hi,

Nice boilerplate to start with.
I am playing with it a little bit for my website and was wondering where the social media icons are coming from.

I would like to add the Github icon and ideally it would match the great style you guys already built.

Thanks!

**Comment by ixartz** [comment]
Hi @epetre,

Sorry, I don't remember exactly where I found the icon.
But, you can totally replace the icons and add a GitHub icon.

Thanks.
