### ISSUE TITLE
Add target prop to NavMenuItem component

### ISSUE THREAD

**Issue by jaqb8** [ixartz/astro-boilerplate-components#6]
### Description:
In the current implementation of the `NavMenuItem` component, there is no way to specify the `target` attribute for the `<a>` tag. This is essential for controlling where the new link will be opened (e.g., in a new tab, same tab, etc.).

### Current Behavior:
```typescript
type INavMenuItemProps = {
  href: string;
  children: string;
};

const NavMenuItem = (props: INavMenuItemProps) => (
  <li className="hover:text-white">
    <a href={props.href}>{props.children}</a>
  </li>
);
```

### Desired Behavior:
Add a target prop to the NavMenuItem component to allow users to specify the target attribute for the <a> tag.

```typescript
type INavMenuItemProps = {
  href: string;
  children: string;
  target?: '_blank' | '_self' | '_parent' | '_top' | string;
};

const NavMenuItem = (props: INavMenuItemProps) => (
  <li className="hover:text-white">
    <a href={props.href} target={props.target}>{props.children}</a>
  </li>
);
```

### Steps to Reproduce:
1. Import and use the NavMenuItem component.
2. Try to specify the target prop.
3. Observe that the target prop is not available.

### Expected Result:
Users should be able to specify the target prop to control where the link will open.

### Actual Result:
The target prop is not available in the current implementation.

### Additional Information:
This enhancement will provide more flexibility to users when using the NavMenuItem component, especially when they want links to open in new tabs or other specific frames.

Note: I'm happy to implement a fix for this issue.

**Comment by ixartz** [comment]
Thank you for making a crystal clear Github issue. It could be great for the project to implement the feature. Totally open to merge your fix.
