### ISSUE TITLE
Getting Started instructions don't make sense, especially for a relative newcomer

### ISSUE THREAD

**Issue by NickHodges** [ixartz/astro-boilerplate-components#8]
The Getting Started instructions probably assume stuff that isn't clear.  

For instance, do you need to have an existing Astro application in a sub-directory when you run the `git clone` command?

It isn't clear how the installation process will integrate at all with, well, anything.

**Comment by NickHodges** [comment]
I kind of figured out how to do things, and I'll submit a pull request.

**Comment by ixartz** [comment]
@NickHodges Thank you for updating the issue. Totally open to pull request.
