### ISSUE TITLE
Compatible with Astro 3?

### ISSUE THREAD

**Issue by NickHodges** [ixartz/astro-boilerplate-components#9]
Is this repository compatible with the new 3.0.x version of Astro?

**Comment by ixartz** [comment]
I didn't take the time to try the new version 3.0.x, totally open to feedback and suggestion.

**Comment by NickHodges** [comment]
Well, I'm fairly new to all of this, but I can tell you that upgrading to Astro 3.0.x brings on all kinds of dependency problems.  I'm not skilled enough yet to know how to deal with that.  Alas.

**Comment by ixartz** [comment]
The project is using Astro 4 now.
